// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Data;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("server.Models.Ad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Discord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<int>("HourEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HourStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseVoiceChannel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WeekDays")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YearsPlaying")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Ads");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9ecf5dff-5a5a-421e-a3fd-deb96d560f4d"),
                            CreatedAt = new DateTime(2022, 9, 21, 10, 49, 18, 601, DateTimeKind.Local).AddTicks(1940),
                            Discord = "Xablau",
                            GameId = new Guid("a29c34f1-ce82-4ef0-84bf-68989b43a4fc"),
                            HourEnd = 1260,
                            HourStart = 1080,
                            Name = "bbJoinha",
                            UseVoiceChannel = true,
                            WeekDays = "[0,1,2,3,4,5,6]",
                            YearsPlaying = 12
                        });
                });

            modelBuilder.Entity("server.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BannerUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a29c34f1-ce82-4ef0-84bf-68989b43a4fc"),
                            BannerUrl = "https://static-cdn.jtvnw.net/ttv-boxart/21779-188x250.jpg",
                            Title = "League of Legends"
                        },
                        new
                        {
                            Id = new Guid("3603085e-3dcd-427b-8439-9d0fa323e4db"),
                            BannerUrl = "https://static-cdn.jtvnw.net/ttv-boxart/32399_IGDB-188x250.jpg",
                            Title = "Counter-Strike"
                        },
                        new
                        {
                            Id = new Guid("d0ea20ba-73fd-42dd-8ee9-794c5b14c02a"),
                            BannerUrl = "https://static-cdn.jtvnw.net/ttv-boxart/516575-188x250.jpg",
                            Title = "Valorant"
                        },
                        new
                        {
                            Id = new Guid("839d57c9-5553-4b14-84c2-071e0e4aa187"),
                            BannerUrl = "https://static-cdn.jtvnw.net/ttv-boxart/18122-285x380.jpg",
                            Title = "World of Warcraft"
                        },
                        new
                        {
                            Id = new Guid("486d3535-bed8-43f6-84fa-08abeacd1d97"),
                            BannerUrl = "https://static-cdn.jtvnw.net/ttv-boxart/511224-285x380.jpg",
                            Title = "Apex Legends"
                        },
                        new
                        {
                            Id = new Guid("60f30faa-550e-4feb-9b33-117d83d23c3c"),
                            BannerUrl = "https://static-cdn.jtvnw.net/ttv-boxart/33214-285x380.jpg",
                            Title = "Fortnite"
                        });
                });

            modelBuilder.Entity("server.Models.Ad", b =>
                {
                    b.HasOne("server.Models.Game", "Game")
                        .WithMany("Ads")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("server.Models.Game", b =>
                {
                    b.Navigation("Ads");
                });
#pragma warning restore 612, 618
        }
    }
}
